POST http://localhost:3000/user/create
Content-Type: application/json

{
  "name": "Outro teste",
  "email": "outrotestke@gmail.com"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/user/2

###
PUT http://localhost:3000/user/2
Content-Type: application/json

{
  "email": "teste@testesss.com"
}

###
DELETE http://localhost:3000/user/8

###
POST http://localhost:3000/user/7/post/create
Content-Type: application/json

{
  "title": "Teste Teste",
  "content": "Teste teste teste",
  "published": true
}
###
PUT http://localhost:3000/user/2/post/3
Content-Type: application/json

{
  "title": "AAAAABBBB",
  "published": true
}

###
GET http://localhost:3000/users/posts
###
GET http://localhost:3000/user/2/post
###
GET http://localhost:3000/user/2/post/2
###
DELETE http://localhost:3000/user/2/post/3